[package]
name = "trackit"
version = "1.0.0"
authors = []

[addresses]
trackit="aaf5681a00ad1b4c62887a4ba51d57f910130d34d9052abddd4546b042813bc2"

[dev-addresses]
trackit="aaf5681a00ad1b4c62887a4ba51d57f910130d34d9052abddd4546b042813bc2"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosToken]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-token'

[dev-dependencies]
